### ISSUE TITLE
Min supported node.js version?

### ISSUE THREAD

**Issue by patrickocoffeyo** [ibm-developer/generator-nodeserver#20]
Hey there! Neat project, I've forked and would like to contribute! What's the minimum supported Node.js version? I didn't see an engine or .nvmrc file, or any min node version documented anywhere so I thought I'd ask.

Thanks, and cheers! 🍻

**Comment by gibfahn** [comment]
I _think_ the minimum supported version would be Node 6.x, but we should definitely add an `engines` field to the `package.json`.

**Comment by patrickocoffeyo** [comment]
@gibfahn I created a PR for this: https://github.com/ibm-developer/generator-nodeserver/pull/21 👍
