### ISSUE TITLE
build script is throwing error

### ISSUE THREAD

**Issue by rumanhassan** [ibm-developer/generator-nodeserver#45]
HI

I have followed the set up docs.
- Set up generator using yeomen.
- Did yo nodeserver
- npm install
- npm run idt:install
- npm run idt:build

BUILD LOG:
node idt.js build

Checking for idt
Running: bx dev build
Creating image heavenues-express-tools based on Dockerfile-tools...
Image will have user ruhassan with id 502 added
OK
Creating a container named 'heavenues-express-tools' from that image...
OK
Starting the 'heavenues-express-tools' container...
OK
Building the project in the current directory started at Wed Mar 28 13:28:58 2018
FAILED
Failed to build the project.
ENOENT: no such file or directory, chmod '/app/node_modules/strong-supervisor/bin/sl-runctl.js'

to solve it i manually installed strong-supervisor node package.

Again i ran npm run idt:build
LOG:
> heavenues@1.0.0 idt:build /Users/ruhassan/heavenues
> node idt.js build

Checking for idt
Running: bx dev build
Creating image heavenues-express-tools based on Dockerfile-tools...
FAILED
An error lstat node_modules_linux/strong-log-transformer: no such file or directory was encountered while building the Docker image.

Can anyone please help.

**Comment by jkingoliver** [comment]
Hi @rumanhassan. What platform are you on?

It would help if you could re-build with trace enabled. Will you build with the command `bx dev build --trace` please and post your results here?

**Comment by rumanhassan** [comment]
Thanks for the reply.
Here is the trace output:

bx dev build --trace
Using these variable values:
01: ContainerName string =
02: ContainerNameRun string = heavenues-express-run
03: ContainerNameTools string = heavenues-express-tools
04: HostPathRun string = .
05: HostPathTools string = .
06: ContainerPathRun string = /app
07: ContainerPathTools string = /app
08: BuildCmdRun string = npm install
09: BuildCmdDebug string = npm install
10: TestCmd string = npm run test
11: DebugCmd string = run-debug
12: RunCmd string =
13: ContainerPortMap string = 3000:3000
14: ContainerPortMapDebug string = 5858:5858
15: ImageNameTools string = heavenues-express-tools
16: ImageNameRun string = heavenues-express-run
17: DockerfileRun string = Dockerfile
18: DockerfileTools string = Dockerfile-tools
19: ContainerMountsRun []map[string]string = [map[./node_modules_linux:/app/node_modules]]
20: ContainerMountsTools []map[string]string = [map[./node_modules_linux:/app/node_modules]]
21: IsDebug bool = false
22: IsTrace bool = true
23: Version string = 0.0.3
24: DeployTarget string =
25: IsForce bool = false
26: Language string =
27: IbmCluster string =
28: ChartPath string = chart/heavenues
29: DockerRegistry string =
30: GeneratedID string =
31: CredsFilepath string =
32: NoOpen bool = false
33: WebAppRoot string =
34: ContainerShell string = /bin/sh
35: ContainerShellTarget string = tools
Creating image heavenues-express-tools based on Dockerfile-tools...
FAILED
An error lstat node_modules_linux/strong-log-transformer: no such file or directory was encountered while building the Docker image.

**Comment by jkingoliver** [comment]
What OS is this?

**Comment by rumanhassan** [comment]
MAC OS X El Capitan - v-10.11.6

**Comment by christiancompton** [comment]
I just tested this on Mojave, and things seem to be working properly.  Please reopen if this appears again.
