### ISSUE TITLE
 npm run idt:install on arch linux

### ISSUE THREAD

**Issue by vamshi9666** [ibm-developer/generator-nodeserver#70]
i used generator-nodeserver on my older ubuntu machine , it worked totally fine with some tweaks. and recently i installed arch linux .when i tried to use same package in it , it ended up saying  
```

[install_deps] Checking for and updating 'apt-get' support on Linux
[install_deps] ERROR: 'apt-get' is not found.  Thats the only linux installer I know, sorry.

```
i dont think , this package is ubuntu specific . so i need help and even changes in documentation

**Comment by jkingoliver** [comment]
Hi @vamshi9666. We only support Ubuntu with our OOTB scripts, so you'll need to install the CLI manually. Please follow instructions here:

https://console.bluemix.net/docs/cli/index.html#overview

The steps described there to install the CLI will replace `npm run idt:install`. Let me know if you run into any other issues. 

I'll make sure our documentation is updated to be more clear. Thanks for opening an issue.
